Design Documents
ScuffleTV/scuffle pull request #2
Opened 2023-01-28 23:18 UTC by TroyKomodo

Works on completing #1 

This PR aims to provide some documents that people can look at to get a better understanding of what this project will do.

2023-01-29 15:21 UTC, TroyKomodo commented
If you can please can you go look at the documents I made, and try to see if you can understand how it works. If anything is unclear it means the documents arent good enough. So if you dont understand anything just say so and ill clarify further in the documents! @ScuffleTV/reviewers

2023-01-29 15:22 UTC, 4w3Official approved these changes
lgtm

2023-01-29 15:39 UTC, DuneWalkerz commented
looks all good to me

2023-01-29 15:45 UTC, IS2511 commented
The general structure is pretty clear, but the nitty gritty details are missing for sure, and the only place they recide is still your head, so you'll probably have to write a lot more docs soon 😄

2023-01-29 15:53 UTC, TroyKomodo commented
> The general structure is pretty clear, but the nitty gritty details are missing for sure, and the only place they recide is still your head, so you'll probably have to write a lot more docs soon 😄

Yeah that is true. I'll try write some more documents on some of the finer details.

2023-01-29 17:00 UTC, mmattbtw requested changes
typo

2023-01-29 17:00 UTC, mmattbtw commented on CONTRIBUTING.md
> +# Snuffle Contribution Guide
```suggestion
# Scuffle Contribution Guide
```

2023-01-30 01:19 UTC, TroyKomodo commented on CONTRIBUTING.md
> +- We can easily maintain and contribute to multiple projects within a single PR or ticket.
Tickets are similar to issues, but tickets more so report that the issue has been acknowledged and is going to be worked on

2023-01-30 01:19 UTC, TroyKomodo commented on CONTRIBUTING.md
> +If you have any questions please ask in the discord server or create an issue on the repo or in the discussion section.
Good idea!

2023-01-30 01:19 UTC, TroyKomodo commented on CONTRIBUTING.md
> +However you do not need to do this for the development stage of your PR. While developing you can commit as many times as you want with any names you like, however once it is ready for merge someone
Well, any PR should be squashed. I'll link a guideline there.

2023-01-30 02:51 UTC, sirinoks commented on CONTRIBUTING.md
> +- We can easily maintain and contribute to multiple projects within a single PR or ticket.
So will it be a label on an issue? Like, how does a new person know what is a ticket and what is not?

2023-01-30 03:10 UTC, sirinoks approved these changes
Pog

2023-01-30 03:37 UTC, mmattbtw approved these changes

2023-01-30 09:27 UTC, IS2511 commented
`CONTRIBUTING.md` still missing: branching strategy/rules (and branch naming), versioning strategy (if any, maybe a problem for later).

2023-01-30 12:19 UTC, 4w3Official approved these changes
ApuBased

2023-01-30 14:11 UTC, treuks approved these changes

2023-01-30 14:11 UTC, mmattbtw approved these changes

2023-01-30 14:15 UTC, IS2511 commented
We could also move the `design` dir to a new `docs` dir but that could easily be done in the future if needed.

2023-01-30 14:15 UTC, merged

2023-01-30 14:16 UTC, IS2511 approved these changes

2023-01-30 14:58 UTC, 4w3Official reviewed
docs(design): Spelling errors as well as grammatical errors fixed

2023-01-30 15:00 UTC, TroyKomodo commented
@4w3Official can u make a new PR with these changes and we can go from there.

2023-01-30 15:00 UTC, 4w3Official commented
sure